ALTER TABLE "Release"
  ADD COLUMN IF NOT EXISTS "acrStatus" TEXT,
  ADD COLUMN IF NOT EXISTS "acrReportJson" TEXT NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "acrFetchedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "acrError" TEXT;
