export const adminNav = [
  { href: "/admin", label: "Home", exact: true },
  { href: "/admin/releases", label: "Releases" },
  { href: "/admin/review-queue", label: "Review Queue" },
  { href: "/admin/action-required", label: "Action Required" },
  { href: "/admin/users", label: "Users" },
  { href: "/admin/artists", label: "Artists" },
  { href: "/admin/labels", label: "Labels" },
  { href: "/admin/documents", label: "Rights & Documents" },
  { href: "/admin/takedowns", label: "Takedowns" },
  { href: "/admin/support", label: "Support" },
  { href: "/admin/royalties", label: "Royalties & Payouts" },
  { href: "/admin/royalty-rules", label: "Royalty Rules" },
  { href: "/admin/wallets", label: "Wallets" },
  { href: "/admin/transactions", label: "Transactions" },
  { href: "/admin/withdrawals", label: "Withdrawals" },
  { href: "/admin/payout-settings", label: "Payout Settings" },
  { href: "/admin/subscriptions", label: "Subscriptions" },
  { href: "/admin/plans", label: "Plans" },
  { href: "/admin/analytics", label: "Analytics" },
  { href: "/admin/system", label: "LabelGrid / System" },
  { href: "/admin/audit", label: "Audit Logs" },
  { href: "/admin/settings", label: "Settings" },
] as const;

export type AdminNavItem = (typeof adminNav)[number];
