services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rdistro
      POSTGRES_PASSWORD: rdistro
      POSTGRES_DB: rdistro
    volumes:
      - rdistro_pg:/var/lib/postgresql/data

volumes:
  rdistro_pg:
