import Link from "next/link";
import { ArrowRight, FileText, Money, Pulse, Storefront, WarningCircle, Wallet } from "@phosphor-icons/react/dist/ssr";
import { requirePermission } from "@/lib/auth/admin";
import { hasPermission } from "@/lib/auth/permissions";
import { prisma } from "@/lib/db";

export const metadata = { title: "Action Required | Admin" }; export const dynamic = "force-dynamic";
const date = (value: Date) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeZone: "UTC" }).format(value);
export default async function ActionRequiredPage() {
  const admin = await requirePermission("admin.access"); const catalog = hasPermission(admin.role, "releases.read"); const documents = hasPermission(admin.role, "documents.manage"); const finance = hasPermission(admin.role, "royalties.read");
  const [qc, changes, failedDelivery, docs, royaltyRows, withdrawals] = await Promise.all([
    catalog ? prisma.release.findMany({ where: { qcStatus: { in: ["warning", "review_required", "failed"] } }, orderBy: { updatedAt: "desc" }, take: 10, include: { artist: { select: { name: true } }, user: { select: { name: true, email: true } } } }) : Promise.resolve([]),
    catalog ? prisma.release.findMany({ where: { OR: [{ status: "labelgrid_changes_required" }, { labelgridReviewStatus: "require_changes" }] }, orderBy: { updatedAt: "desc" }, take: 10, include: { artist: { select: { name: true } }, user: { select: { name: true, email: true } }, _count: { select: { reviewIssues: true } } } }) : Promise.resolve([]),
    catalog ? prisma.release.findMany({ where: { OR: [{ deliveryState: "action_needed" }, { status: { in: ["sync_error", "error"] } }, { syncError: { not: null } }] }, orderBy: { updatedAt: "desc" }, take: 10, include: { artist: { select: { name: true } }, user: { select: { name: true, email: true } } } }) : Promise.resolve([]),
    documents ? prisma.releaseDocument.findMany({ where: { reviewStatus: { in: ["pending", "replacement_requested"] } }, orderBy: { createdAt: "desc" }, take: 10, include: { release: { include: { user: { select: { name: true, email: true } }, artist: { select: { name: true } } } } } }) : Promise.resolve([]),
    finance ? prisma.royaltyTransaction.findMany({ where: { matchStatus: { in: ["unmatched", "conflict"] } }, orderBy: { createdAt: "desc" }, take: 10, include: { royaltyPeriod: { select: { id: true, period: true } }, release: { select: { title: true } } } }) : Promise.resolve([]),
    finance ? prisma.withdrawal.findMany({ where: { status: "declined" }, orderBy: { updatedAt: "desc" }, take: 10, include: { user: { select: { name: true, email: true } } } }) : Promise.resolve([]),
  ]);
  const [qcCount, changesCount, failedCount, docsCount, royaltyCount, payoutCount] = await Promise.all([
    catalog ? prisma.release.count({ where: { qcStatus: { in: ["warning", "review_required", "failed"] } } }) : 0,
    catalog ? prisma.release.count({ where: { OR: [{ status: "labelgrid_changes_required" }, { labelgridReviewStatus: "require_changes" }] } }) : 0,
    catalog ? prisma.release.count({ where: { OR: [{ deliveryState: "action_needed" }, { status: { in: ["sync_error", "error"] } }, { syncError: { not: null } }] } }) : 0,
    documents ? prisma.releaseDocument.count({ where: { reviewStatus: { in: ["pending", "replacement_requested"] } } }) : 0,
    finance ? prisma.royaltyTransaction.count({ where: { matchStatus: { in: ["unmatched", "conflict"] } } }) : 0,
    finance ? prisma.withdrawal.count({ where: { status: "declined" } }) : 0,
  ]);
  const metrics = [
    ...(catalog ? [{ label: "Preflight QC failures", count: qcCount, href: "/admin/releases?filter=qc_flagged", icon: Pulse }, { label: "LabelGrid changes", count: changesCount, href: "/admin/releases?filter=changes_required", icon: WarningCircle }, { label: "Failed deliveries", count: failedCount, href: "/admin/releases?filter=sync_issues", icon: Storefront }] : []),
    ...(documents ? [{ label: "Document requests", count: docsCount, href: "/admin/documents?status=pending", icon: FileText }] : []),
    ...(finance ? [{ label: "Unmatched royalties", count: royaltyCount, href: "/admin/royalties", icon: Money }, { label: "Payout problems", count: payoutCount, href: "/admin/withdrawals?status=declined", icon: Wallet }] : []),
  ];
  return <div className="mx-auto max-w-[1400px] space-y-6"><header className="border-b border-border pb-6"><div className="flex items-center gap-2 text-amber-700"><WarningCircle size={18} weight="fill" /><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em]">Exception operations</span></div><h1 className="mt-3 text-3xl font-semibold tracking-[-0.045em]">Action required</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">One role-aware workspace for catalog, compliance, royalty and payout exceptions that need a human decision.</p></header>
    <section className="grid border border-border bg-card sm:grid-cols-2 xl:grid-cols-6">{metrics.map((metric) => { const Icon = metric.icon; return <Link key={metric.label} href={metric.href} className="group border-b border-border p-4 sm:border-r xl:border-b-0"><div className="flex justify-between gap-2"><p className="max-w-32 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{metric.label}</p><Icon className={metric.count ? "text-amber-700" : "text-muted-foreground"} /></div><p className={`mt-4 text-3xl font-semibold ${metric.count ? "text-amber-800" : ""}`}>{metric.count.toLocaleString()}</p></Link>; })}</section>
    {!metrics.some((metric) => metric.count) ? <section className="grid min-h-56 place-items-center border border-dashed border-border bg-card"><div className="text-center"><Pulse className="mx-auto text-emerald-700" size={28} /><h2 className="mt-3 font-semibold">No visible exceptions</h2><p className="mt-1 text-sm text-muted-foreground">The queues available to your role are clear.</p></div></section> : null}
    <div className="grid gap-5 xl:grid-cols-2">
      {catalog ? <ExceptionPanel title="Preflight QC failures" count={qcCount} href="/admin/releases?filter=qc_flagged">{qc.map((release) => <ExceptionRow key={release.id} href={`/admin/releases/${release.id}#qc`} title={release.title} detail={`${release.artist?.name ?? "Artist not assigned"} / ${release.user.email}`} state={release.qcStatus ?? "QC flagged"} />)}</ExceptionPanel> : null}
      {catalog ? <ExceptionPanel title="LabelGrid changes required" count={changesCount} href="/admin/releases?filter=changes_required">{changes.map((release) => <ExceptionRow key={release.id} href={`/admin/releases/${release.id}`} title={release.title} detail={`${release._count.reviewIssues} review issues / ${release.user.email}`} state={release.labelgridReviewStatus ?? release.status} />)}</ExceptionPanel> : null}
      {catalog ? <ExceptionPanel title="Delivery and sync failures" count={failedCount} href="/admin/releases?filter=sync_issues">{failedDelivery.map((release) => <ExceptionRow key={release.id} href={`/admin/releases/${release.id}#delivery`} title={release.title} detail={release.syncError ?? `${release.artist?.name ?? "Artist not assigned"} / ${release.user.email}`} state={release.deliveryState ?? release.status} danger />)}</ExceptionPanel> : null}
      {documents ? <ExceptionPanel title="Documentation requests" count={docsCount} href="/admin/documents?status=pending">{docs.map((document) => <ExceptionRow key={document.id} href={`/admin/documents/${document.id}`} title={document.kind} detail={`${document.release.title} / ${document.release.user.email}`} state={document.reviewStatus} />)}</ExceptionPanel> : null}
      {finance ? <ExceptionPanel title="Unmatched royalty transactions" count={royaltyCount} href="/admin/royalties">{royaltyRows.map((row) => <ExceptionRow key={row.id} href={`/admin/royalties/${row.royaltyPeriod.id}?status=${row.matchStatus}`} title={row.trackTitle || row.release?.title || "Unmatched royalty row"} detail={`${row.royaltyPeriod.period} / ${row.isrc ?? "No ISRC"} / ${row.retailer ?? "No DSP"}`} state={row.matchStatus} />)}</ExceptionPanel> : null}
      {finance ? <ExceptionPanel title="Payout problems" count={payoutCount} href="/admin/withdrawals?status=declined">{withdrawals.map((withdrawal) => <ExceptionRow key={withdrawal.id} href={`/admin/withdrawals?q=${withdrawal.reference}`} title={`${withdrawal.currency} ${withdrawal.amount.toString()} withdrawal`} detail={`${withdrawal.user.name} / ${withdrawal.user.email} / ${date(withdrawal.updatedAt)}`} state={withdrawal.failureReason ?? "Declined"} danger />)}</ExceptionPanel> : null}
    </div></div>;
}
function ExceptionPanel({ title, count, href, children }: { title: string; count: number; href: string; children: React.ReactNode }) { return <section className="overflow-hidden border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-[11px] text-muted-foreground">Showing up to 10 of {count.toLocaleString()}</p></div><Link href={href} className="text-xs font-semibold hover:underline">Open queue</Link></div><div className="divide-y divide-border">{count ? children : <p className="px-4 py-10 text-center text-xs text-muted-foreground">No exceptions in this queue.</p>}</div></section>; }
function ExceptionRow({ href, title, detail, state, danger = false }: { href: string; title: string; detail: string; state: string; danger?: boolean }) { return <Link href={href} className="group grid gap-2 px-4 py-3 hover:bg-muted/30 sm:grid-cols-[1fr_auto] sm:items-center"><div className="min-w-0"><p className="truncate text-sm font-semibold">{title}</p><p className="mt-1 truncate text-[10px] text-muted-foreground">{detail}</p></div><div className="flex items-center gap-2"><span className={`max-w-52 truncate text-[10px] font-semibold capitalize ${danger ? "text-red-700" : "text-amber-700"}`}>{state.replaceAll("_", " ")}</span><ArrowRight className="text-muted-foreground transition group-hover:translate-x-0.5" /></div></Link>; }
