"use client";

import { useState } from "react";
import { CheckCircle, FloppyDisk } from "@phosphor-icons/react";
import type { PayoutMethod, PayoutPolicy } from "@/lib/payout-settings";
import { payoutMethodLabel } from "@/lib/payout-methods";

const methods: PayoutMethod[] = ["wise", "paypal", "payoneer"];

export function PayoutConfigurationForm({ initial }: { initial: PayoutPolicy }) {
  const [policy, setPolicy] = useState(initial);
  const [state, setState] = useState<"idle" | "saving" | "saved">("idle");
  const [error, setError] = useState("");
  const updateMethod = (method: PayoutMethod, field: string, value: string | boolean) => setPolicy((current) => ({ ...current, methods: { ...current.methods, [method]: { ...current.methods[method], [field]: value } } }));
  return <form className="space-y-6" onSubmit={async (event) => { event.preventDefault(); setState("saving"); setError(""); const response = await fetch("/api/admin/settings/payouts", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(policy) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not save payout settings."); setState("idle"); } else setState("saved"); }}>
    <section className="grid gap-5 border border-border bg-card p-5 lg:grid-cols-[.55fr_1.45fr]"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">Global policy</p><h2 className="mt-2 text-lg font-semibold">Withdrawal availability</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Applied by the withdrawal API to every new request.</p></div><div className="grid gap-4"><label className="text-xs font-semibold">Withdrawal currency<select value={policy.currency} onChange={(event) => setPolicy({ ...policy, currency: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-border bg-background px-3 text-sm"><option value="USD">USD</option></select></label><label className="text-xs font-semibold">Availability rules<textarea value={policy.availabilityRules} onChange={(event) => setPolicy({ ...policy, availabilityRules: event.target.value })} maxLength={2000} rows={3} className="mt-1 w-full rounded-md border border-border bg-background p-3 text-sm font-normal" /></label></div></section>
    <section className="overflow-hidden border border-border bg-card"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-semibold">Payout methods</h2><p className="mt-1 text-xs text-muted-foreground">Disabled methods cannot be selected or used for new withdrawals.</p></div><div className="divide-y divide-border">{methods.map((method) => { const item = policy.methods[method]; return <article key={method} className="grid gap-5 p-5 xl:grid-cols-[220px_1fr]"><div><div className="flex items-center justify-between gap-3"><h3 className="text-base font-semibold">{payoutMethodLabel(method)}</h3><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={item.enabled} onChange={(event) => updateMethod(method, "enabled", event.target.checked)} className="size-4 accent-foreground" /> Enabled</label></div><p className="mt-2 text-xs leading-5 text-muted-foreground">Changes affect future payout destination updates and withdrawal requests.</p></div><div className="grid gap-4 md:grid-cols-3"><label className="text-xs font-semibold">Minimum<input inputMode="decimal" value={item.minimum} onChange={(event) => updateMethod(method, "minimum", event.target.value)} className="mt-1 h-10 w-full rounded-md border border-border bg-background px-3 text-sm font-normal" /></label><label className="text-xs font-semibold">Fixed fee<input inputMode="decimal" value={item.fixedFee} onChange={(event) => updateMethod(method, "fixedFee", event.target.value)} className="mt-1 h-10 w-full rounded-md border border-border bg-background px-3 text-sm font-normal" /></label><label className="text-xs font-semibold">Percentage fee<input inputMode="decimal" value={item.percentageFee} onChange={(event) => updateMethod(method, "percentageFee", event.target.value)} className="mt-1 h-10 w-full rounded-md border border-border bg-background px-3 text-sm font-normal" /></label><label className="text-xs font-semibold md:col-span-3">Payout instructions<textarea value={item.instructions} onChange={(event) => updateMethod(method, "instructions", event.target.value)} rows={2} className="mt-1 w-full rounded-md border border-border bg-background p-3 text-sm font-normal" /></label><label className="text-xs font-semibold md:col-span-3">Estimated processing text<textarea value={item.processingText} onChange={(event) => updateMethod(method, "processingText", event.target.value)} rows={2} className="mt-1 w-full rounded-md border border-border bg-background p-3 text-sm font-normal" /></label></div></article>; })}</div></section>
    {error ? <p role="alert" className="text-sm font-semibold text-red-700">{error}</p> : null}<div className="flex items-center gap-3"><button disabled={state === "saving"} className="flex h-10 items-center gap-2 rounded-md bg-foreground px-4 text-xs font-semibold text-background disabled:opacity-50"><FloppyDisk /> {state === "saving" ? "Saving" : "Save payout settings"}</button>{state === "saved" ? <span className="flex items-center gap-1.5 text-xs font-semibold text-emerald-700"><CheckCircle weight="fill" /> Settings saved</span> : null}</div>
  </form>;
}
