"use client";

import { useState } from "react";
import { CheckCircle, FloppyDisk } from "@phosphor-icons/react";
import type { ConfiguredPlan } from "@/lib/plans";

type FormPlan = ConfiguredPlan & { royaltyCommissionPercent: number };
export function PlanConfigurationForm({ initial }: { initial: FormPlan[] }) {
  const [plans, setPlans] = useState(initial); const [state, setState] = useState<"idle" | "saving" | "saved">("idle"); const [error, setError] = useState("");
  const update = (id: string, field: string, value: unknown) => setPlans((current) => current.map((plan) => plan.id === id ? { ...plan, [field]: value } : plan));
  return <form className="space-y-6" onSubmit={async (event) => { event.preventDefault(); setState("saving"); setError(""); const response = await fetch("/api/admin/settings/plans", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ plans }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not save plans."); setState("idle"); } else setState("saved"); }}>
    <section className="divide-y divide-border border border-border bg-card">{plans.map((plan) => <article key={plan.id} className="grid gap-6 p-5 xl:grid-cols-[220px_1fr]"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">{plan.id}</p><input aria-label={`${plan.id} plan name`} value={plan.name} onChange={(event) => update(plan.id, "name", event.target.value)} className="mt-2 h-10 w-full border border-border bg-background px-3 text-lg font-semibold" /><div className="mt-4 flex flex-wrap gap-4"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={plan.active} onChange={(event) => update(plan.id, "active", event.target.checked)} /> Active</label><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={plan.hidden} onChange={(event) => update(plan.id, "hidden", event.target.checked)} /> Hidden</label></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <Field label="Price"><input value={plan.price} inputMode="decimal" onChange={(event) => update(plan.id, "price", event.target.value)} className="mt-1 h-10 w-full border border-border bg-background px-3 text-xs font-normal normal-case tracking-normal text-foreground" /></Field><Field label="Billing interval"><select value={plan.billingInterval} onChange={(event) => update(plan.id, "billingInterval", event.target.value)} className="mt-1 h-10 w-full border border-border bg-background px-3 text-xs font-normal normal-case tracking-normal text-foreground"><option value="forever">Forever</option><option value="month">Monthly</option><option value="year">Yearly</option></select></Field><Field label="Artist limit"><input value={plan.artists ?? ""} inputMode="numeric" placeholder="Unlimited" onChange={(event) => update(plan.id, "artists", event.target.value ? Number(event.target.value) : null)} className="mt-1 h-10 w-full border border-border bg-background px-3 text-xs font-normal normal-case tracking-normal text-foreground" /></Field><Field label="Monthly release limit"><input value={plan.releasesPerMonth ?? ""} inputMode="numeric" placeholder="Unlimited" onChange={(event) => update(plan.id, "releasesPerMonth", event.target.value ? Number(event.target.value) : null)} className="mt-1 h-10 w-full border border-border bg-background px-3 text-xs font-normal normal-case tracking-normal text-foreground" /></Field>
      <Field label="Royalty commission percent"><input value={plan.royaltyCommissionPercent} inputMode="decimal" onChange={(event) => update(plan.id, "royaltyCommissionPercent", Number(event.target.value))} className="mt-1 h-10 w-full border border-border bg-background px-3 text-xs font-normal normal-case tracking-normal text-foreground" /></Field><Field label="Stripe Price ID"><input value={plan.stripePriceId ?? ""} onChange={(event) => update(plan.id, "stripePriceId", event.target.value || null)} placeholder={plan.id === "free" ? "Not required" : "price_..."} className="mt-1 h-10 w-full border border-border bg-background px-3 font-mono text-xs font-normal normal-case tracking-normal text-foreground" /></Field><div className="flex items-end gap-4 pb-2"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={plan.analytics} onChange={(event) => update(plan.id, "analytics", event.target.checked)} /> Analytics</label><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={plan.priorityReview} onChange={(event) => update(plan.id, "priorityReview", event.target.checked)} /> Priority review</label></div><Field label="Features, one per line" wide><textarea value={plan.features.join("\n")} onChange={(event) => update(plan.id, "features", event.target.value.split("\n").map((item) => item.trim()).filter(Boolean))} rows={4} className="mt-1 w-full border border-border bg-background p-3 text-xs font-normal normal-case tracking-normal text-foreground" /></Field>
    </div></article>)}</section>{error ? <p role="alert" className="text-sm font-semibold text-red-700">{error}</p> : null}<div className="flex items-center gap-3"><button disabled={state === "saving"} className="flex h-10 items-center gap-2 bg-foreground px-4 text-xs font-semibold text-background disabled:opacity-50"><FloppyDisk /> {state === "saving" ? "Saving" : "Save plan catalog"}</button>{state === "saved" ? <span className="flex items-center gap-1.5 text-xs font-semibold text-emerald-700"><CheckCircle weight="fill" /> Plans saved</span> : null}</div>
  </form>;
}
function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={`text-[10px] font-semibold uppercase tracking-wide text-muted-foreground ${wide ? "md:col-span-2 xl:col-span-4" : ""}`}>{label}{children}</label>; }
