"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowUp, CheckCircle } from "@phosphor-icons/react";

type Option = { id: string; label: string };
const controlClass = "mt-1 h-10 w-full border border-border bg-background px-2 text-xs font-normal normal-case tracking-normal text-foreground";
export function SupportOperationsForm({ ticketId, initial, staff, releases, artists }: { ticketId: string; initial: { status: string; priority: string; assignedToId: string | null; releaseId: string | null; artistId: string | null; escalated: boolean }; staff: Option[]; releases: Option[]; artists: Option[] }) {
  const router = useRouter(); const [form, setForm] = useState(initial); const [note, setNote] = useState(""); const [state, setState] = useState<"idle" | "saving" | "saved">("idle"); const [error, setError] = useState("");
  const save = async (extra: Record<string, unknown> = {}) => { setState("saving"); setError(""); const response = await fetch(`/api/admin/support/${ticketId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, internalNote: note.trim() || undefined, ...extra }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not update ticket."); setState("idle"); } else { setNote(""); setState("saved"); router.refresh(); } };
  return <section className="border border-border bg-card"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-semibold">Ticket operations</h2><p className="mt-1 text-xs text-muted-foreground">Assignment, linked catalog data and notes are visible to staff only.</p></div><div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">
    <Control label="Status"><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className={controlClass}><option value="open">Open</option><option value="in_progress">In progress</option><option value="answered">Awaiting user</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></Control>
    <Control label="Priority"><select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })} className={controlClass}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Control>
    <Control label="Assigned staff"><select value={form.assignedToId ?? ""} onChange={(event) => setForm({ ...form, assignedToId: event.target.value || null })} className={controlClass}><option value="">Unassigned</option>{staff.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Control>
    <Control label="Linked release"><select value={form.releaseId ?? ""} onChange={(event) => setForm({ ...form, releaseId: event.target.value || null })} className={controlClass}><option value="">No linked release</option>{releases.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Control>
    <Control label="Linked artist"><select value={form.artistId ?? ""} onChange={(event) => setForm({ ...form, artistId: event.target.value || null })} className={controlClass}><option value="">No linked artist</option>{artists.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Control>
    <Control label="Internal note"><textarea value={note} onChange={(event) => setNote(event.target.value)} rows={3} maxLength={4000} className="mt-1 w-full border border-border bg-background p-2 text-xs font-normal normal-case tracking-normal text-foreground" /></Control>
  </div><div className="flex flex-wrap items-center gap-3 border-t border-border px-5 py-4"><button type="button" onClick={() => void save()} disabled={state === "saving"} className="h-9 bg-foreground px-4 text-xs font-semibold text-background disabled:opacity-50">{state === "saving" ? "Saving" : "Save operations"}</button><button type="button" onClick={() => void save({ escalated: !form.escalated })} disabled={state === "saving"} className={`flex h-9 items-center gap-2 border px-4 text-xs font-semibold ${form.escalated ? "border-amber-300 text-amber-800" : "border-red-300 text-red-700"}`}><ArrowUp /> {form.escalated ? "Remove escalation" : "Escalate"}</button>{state === "saved" ? <span className="flex items-center gap-1 text-xs font-semibold text-emerald-700"><CheckCircle weight="fill" /> Saved</span> : null}{error ? <p className="w-full text-xs font-semibold text-red-700">{error}</p> : null}</div></section>;
}
function Control({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}{children}</label>; }
