import Link from "next/link";
import { Prisma, type WalletTransactionStatus, type WalletTransactionType } from "@prisma/client";
import { formatShortDate } from "@/lib/admin/format";
import { requirePermission } from "@/lib/auth/admin";
import { prisma } from "@/lib/db";
import { calculateWalletBalances } from "@/lib/wallet";
import { describePayoutDestination, payoutMethodLabel } from "@/lib/payout-methods";

export const metadata = { title: "Wallets | Admin" };
export const dynamic = "force-dynamic";
type Props = { searchParams: Promise<{ q?: string; type?: string; status?: string; page?: string }> };
const types: WalletTransactionType[] = ["royalty_credit", "withdrawal", "adjustment", "reversal"];
const statuses: WalletTransactionStatus[] = ["pending", "available", "processing", "paid", "declined", "reversed"];
const money = (value: Prisma.Decimal.Value) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 6 }).format(Number(value.toString()));

export default async function AdminWalletsPage({ searchParams }: Props) {
  await requirePermission("royalties.read");
  const sp = await searchParams;
  const q = sp.q?.trim() ?? "";
  const type = types.includes(sp.type as WalletTransactionType) ? sp.type as WalletTransactionType : undefined;
  const status = statuses.includes(sp.status as WalletTransactionStatus) ? sp.status as WalletTransactionStatus : undefined;
  const page = Math.max(1, Number(sp.page ?? "1") || 1);
  const userWhere = { role: "user" as const, ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { email: { contains: q, mode: "insensitive" as const } }] } : {}) };
  const transactionWhere = { ...(type ? { type } : {}), ...(status ? { status } : {}), ...(q ? { user: { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { email: { contains: q, mode: "insensitive" as const } }] } } : {}) };
  const [globalGroups, users, transactions, transactionTotal] = await Promise.all([
    prisma.walletTransaction.groupBy({ by: ["direction", "status", "type"], _sum: { amount: true } }),
    prisma.user.findMany({ where: userWhere, orderBy: { name: "asc" }, take: 25, select: { id: true, name: true, email: true, payoutMethod: true, payoutEmail: true, payoutWiseAccount: true, payoutPayoneerAccount: true, payoutBankName: true, payoutBankAccountNumber: true } }),
    prisma.walletTransaction.findMany({ where: transactionWhere, orderBy: { createdAt: "desc" }, skip: (page - 1) * 50, take: 50, include: { user: { select: { id: true, name: true, email: true } } } }),
    prisma.walletTransaction.count({ where: transactionWhere }),
  ]);
  const userGroups = users.length ? await prisma.walletTransaction.groupBy({ by: ["userId", "direction", "status", "type"], where: { userId: { in: users.map((user) => user.id) } }, _sum: { amount: true } }) : [];
  const global = calculateWalletBalances(globalGroups);
  const totalBalance = global.available.plus(global.pending);
  const pages = Math.max(1, Math.ceil(transactionTotal / 50));
  const href = (nextPage: number) => `/admin/wallets?${new URLSearchParams({ ...(q ? { q } : {}), ...(type ? { type } : {}), ...(status ? { status } : {}), ...(nextPage > 1 ? { page: String(nextPage) } : {}) })}`;

  return <div className="space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border pb-5"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Financial overview</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">User wallets</h1><p className="mt-1 text-sm text-muted-foreground">Balances are calculated from auditable ledger entries and cannot be overwritten directly.</p></div><Link href="/admin/royalties" className="h-9 border border-border px-4 py-2 text-xs font-semibold hover:border-foreground">Royalty ledger</Link></header>
    <section className="grid border border-border bg-card sm:grid-cols-2 xl:grid-cols-5"><Metric label="Total balances" value={money(totalBalance)} /><Metric label="Available" value={money(global.available)} /><Metric label="Pending" value={money(global.pending)} /><Metric label="Lifetime earned" value={money(global.lifetimeEarnings)} /><Metric label="Paid lifetime" value={money(global.lifetimeWithdrawn)} /></section>
    <section className="border border-border bg-card p-4"><form className="grid gap-2 sm:grid-cols-[1fr_180px_180px_auto]"><input name="q" defaultValue={q} placeholder="User name or email" aria-label="Search wallet users" className="h-10 border border-border bg-background px-3 text-sm outline-none focus:border-foreground/40" /><select name="type" defaultValue={type ?? ""} aria-label="Transaction type" className="h-10 border border-border bg-background px-3 text-xs"><option value="">All transaction types</option>{types.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select><select name="status" defaultValue={status ?? ""} aria-label="Transaction status" className="h-10 border border-border bg-background px-3 text-xs"><option value="">All statuses</option>{statuses.map((value) => <option key={value} value={value}>{value}</option>)}</select><button className="h-10 bg-foreground px-5 text-xs font-semibold text-background">Apply filters</button></form></section>
    <section className="border border-border bg-card"><div className="flex justify-between border-b border-border px-4 py-3"><div><h2 className="text-sm font-semibold">Wallet accounts</h2><p className="mt-1 text-[11px] text-muted-foreground">First 25 matching users, derived from their transaction ledger.</p></div>{q ? <Link href="/admin/wallets" className="text-xs font-semibold hover:underline">Clear search</Link> : null}</div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-xs"><thead className="border-b border-border bg-muted/40 text-[10px] uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">User</th><th className="px-3 py-3 text-right">Available</th><th className="px-3 py-3 text-right">Pending</th><th className="px-3 py-3 text-right">Lifetime earned</th><th className="px-3 py-3 text-right">Paid</th><th className="px-3 py-3">Payout destination</th><th className="px-4 py-3 text-right">Profile</th></tr></thead><tbody className="divide-y divide-border">{!users.length ? <tr><td colSpan={7} className="px-4 py-12 text-center text-muted-foreground">No users match this search.</td></tr> : users.map((user) => { const balance = calculateWalletBalances(userGroups.filter((group) => group.userId === user.id)); return <tr key={user.id} className="hover:bg-muted/25"><td className="px-4 py-3"><p className="font-semibold">{user.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{user.email}</p></td><td className="px-3 py-3 text-right font-semibold tabular-nums">{money(balance.available)}</td><td className="px-3 py-3 text-right tabular-nums">{money(balance.pending)}</td><td className="px-3 py-3 text-right tabular-nums">{money(balance.lifetimeEarnings)}</td><td className="px-3 py-3 text-right tabular-nums">{money(balance.lifetimeWithdrawn)}</td><td className="px-3 py-3"><p>{payoutMethodLabel(user.payoutMethod)}</p><p className="mt-1 text-[10px] text-muted-foreground">{describePayoutDestination(user)}</p></td><td className="px-4 py-3 text-right"><Link href={`/admin/users/${user.id}`} className="font-semibold hover:underline">View user</Link></td></tr>; })}</tbody></table></div></section>
    <section className="border border-border bg-card"><div className="flex justify-between border-b border-border px-4 py-3"><div><h2 className="text-sm font-semibold">Global wallet ledger</h2><p className="mt-1 text-[11px] text-muted-foreground">Royalty credits, withdrawals, adjustments, and reversals.</p></div><span className="text-xs text-muted-foreground">{transactionTotal.toLocaleString()} entries</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="border-b border-border bg-muted/40 text-[10px] uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Date</th><th className="px-3 py-3">User</th><th className="px-3 py-3">Entry</th><th className="px-3 py-3">Source</th><th className="px-3 py-3">Status</th><th className="px-4 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-border">{!transactions.length ? <tr><td colSpan={6} className="px-4 py-12 text-center text-muted-foreground">No transactions match these filters.</td></tr> : transactions.map((entry) => <tr key={entry.id} className="hover:bg-muted/25"><td className="px-4 py-3 text-muted-foreground">{formatShortDate(entry.createdAt)}</td><td className="px-3 py-3"><Link href={`/admin/users/${entry.user.id}`} className="font-semibold hover:underline">{entry.user.name}</Link><p className="mt-1 text-[10px] text-muted-foreground">{entry.user.email}</p></td><td className="px-3 py-3"><p className="font-semibold">{entry.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{entry.type.replaceAll("_", " ")}</p></td><td className="px-3 py-3 font-mono text-[10px]"><p>{entry.sourceType.replaceAll("_", " ")}</p><p className="mt-1 max-w-48 truncate text-muted-foreground">{entry.sourceId}</p></td><td className="px-3 py-3 uppercase">{entry.status}</td><td className={`px-4 py-3 text-right font-semibold tabular-nums ${entry.direction === "credit" ? "text-emerald-800" : "text-red-700"}`}>{entry.direction === "credit" ? "+" : "-"}{money(entry.amount)}</td></tr>)}</tbody></table></div></section>
    {pages > 1 ? <nav aria-label="Wallet ledger pagination" className="flex items-center justify-between text-xs"><p className="text-muted-foreground">Page {page} of {pages}</p><div className="flex gap-2">{page > 1 ? <Link href={href(page - 1)} className="border border-border px-3 py-2 font-semibold">Previous</Link> : null}{page < pages ? <Link href={href(page + 1)} className="border border-border px-3 py-2 font-semibold">Next</Link> : null}</div></nav> : null}
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="border-b border-border px-4 py-3 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 truncate text-lg font-semibold tabular-nums">{value}</p></div>; }
