import Link from "next/link";
import { RoyaltyRuleForm } from "@/components/admin/royalty-rule-form";
import { formatShortDate } from "@/lib/admin/format";
import { requirePermission } from "@/lib/auth/admin";
import { hasPermission } from "@/lib/auth/permissions";
import { prisma } from "@/lib/db";

export const metadata = { title: "Royalty Rules | Admin" };
type Props = { searchParams: Promise<{ scope?: string; state?: string }> };

export default async function RoyaltyRulesPage({ searchParams }: Props) {
  const admin = await requirePermission("royalties.read");
  const canWrite = hasPermission(admin.role, "royalties.write");
  const sp = await searchParams;
  const scope = ["global", "plan", "user"].includes(sp.scope ?? "") ? sp.scope : undefined;
  const state = sp.state === "active" || sp.state === "historical" ? sp.state : undefined;
  const [rules, users, auditEvents, scopeGroups, activeRuleCount] = await Promise.all([
    prisma.royaltyRule.findMany({ where: { ...(scope ? { scope: scope as "global" | "plan" | "user" } : {}), ...(state ? { active: state === "active" } : {}) }, orderBy: [{ active: "desc" }, { effectiveFrom: "desc" }, { version: "desc" }], include: { user: { select: { id: true, name: true, email: true } }, _count: { select: { transactions: true } } } }),
    canWrite ? prisma.user.findMany({ where: { role: "user", terminated: false }, select: { id: true, name: true, email: true }, orderBy: { name: "asc" }, take: 500 }) : Promise.resolve([]),
    prisma.auditLog.findMany({ where: { targetType: "royalty_rule" }, orderBy: { createdAt: "desc" }, take: 30, include: { actor: { select: { name: true } } } }),
    prisma.royaltyRule.groupBy({ by: ["scope"], _count: true }),
    prisma.royaltyRule.count({ where: { active: true } }),
  ]);
  const scopeCount = (value: "global" | "plan" | "user") => scopeGroups.find((group) => group.scope === value)?._count ?? 0;
  const counts = { global: scopeCount("global"), plan: scopeCount("plan"), user: scopeCount("user"), active: activeRuleCount };
  const filterHref = (nextScope?: string, nextState?: string) => `/admin/royalty-rules?${new URLSearchParams({ ...(nextScope ? { scope: nextScope } : {}), ...(nextState ? { state: nextState } : {}) })}`;

  return <div className="space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border pb-5"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Finance policy</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Royalty rules</h1><p className="mt-1 text-sm text-muted-foreground">Versioned commission and revenue-share policy used during royalty calculation.</p></div><Link href="/admin/royalties" className="h-9 border border-border px-4 py-2 text-xs font-semibold hover:border-foreground">Royalty ledger</Link></header>
    <section className="grid border border-border bg-card sm:grid-cols-4"><Metric label="Active" value={counts.active} /><Metric label="Global" value={counts.global} /><Metric label="Plan" value={counts.plan} /><Metric label="User" value={counts.user} /></section>
    <section className="border border-border bg-foreground p-4 text-background"><h2 className="text-sm font-semibold">Rule precedence</h2><div className="mt-3 grid gap-2 text-xs sm:grid-cols-3"><div className="border border-background/20 p-3"><b>1. User-specific</b><p className="mt-1 text-background/60">Overrides plan and global policy for that account.</p></div><div className="border border-background/20 p-3"><b>2. Plan-specific</b><p className="mt-1 text-background/60">Applies when no user-specific rule matches.</p></div><div className="border border-background/20 p-3"><b>3. Global</b><p className="mt-1 text-background/60">Fallback when no narrower rule applies.</p></div></div><p className="mt-3 text-[10px] text-background/55">Eligibility is evaluated at the royalty period end date. Published transactions retain their applied rule ID and version.</p></section>
    <nav className="flex flex-wrap gap-1" aria-label="Rule filters"><Link href={filterHref(undefined, state)} className={`border px-3 py-2 text-[11px] font-semibold ${!scope ? "border-foreground bg-foreground text-background" : "border-border bg-card"}`}>All scopes</Link>{["global", "plan", "user"].map((item) => <Link key={item} href={filterHref(item, state)} className={`border px-3 py-2 text-[11px] font-semibold capitalize ${scope === item ? "border-foreground bg-foreground text-background" : "border-border bg-card"}`}>{item}</Link>)}<span className="mx-1 border-l border-border" /><Link href={filterHref(scope, "active")} className={`border px-3 py-2 text-[11px] font-semibold ${state === "active" ? "border-foreground bg-foreground text-background" : "border-border bg-card"}`}>Active</Link><Link href={filterHref(scope, "historical")} className={`border px-3 py-2 text-[11px] font-semibold ${state === "historical" ? "border-foreground bg-foreground text-background" : "border-border bg-card"}`}>Historical</Link></nav>
    {canWrite ? <RoyaltyRuleForm users={users} /> : null}
    <section className="overflow-hidden border border-border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="border-b border-border bg-muted/40 text-[10px] uppercase tracking-[0.12em] text-muted-foreground"><tr><th className="px-4 py-3">Rule and version</th><th className="px-3 py-3">Scope target</th><th className="px-3 py-3">Method</th><th className="px-3 py-3">Adjustments</th><th className="px-3 py-3">Effective window</th><th className="px-3 py-3">Usage</th><th className="px-4 py-3">State</th></tr></thead><tbody className="divide-y divide-border">{!rules.length ? <tr><td colSpan={7} className="px-4 py-16 text-center text-sm text-muted-foreground">No rules match this view.</td></tr> : rules.map((rule) => <tr key={rule.id} className="align-top hover:bg-muted/25"><td className="px-4 py-3"><p className="font-semibold">{rule.name}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">Version {rule.version} / {rule.id}</p></td><td className="px-3 py-3"><p className="font-semibold capitalize">{rule.scope}</p><p className="mt-1 text-[10px] text-muted-foreground">{rule.scope === "user" ? rule.user ? `${rule.user.name} / ${rule.user.email}` : "User removed" : rule.scope === "plan" ? rule.planId : "All eligible users"}</p></td><td className="px-3 py-3 font-semibold">{rule.commissionRate !== null ? `${rule.commissionRate.toString()}% commission` : `${rule.revenueShareRate?.toString() ?? "100"}% user share`}</td><td className="px-3 py-3"><p>Fixed: {rule.fixedAdjustment.toString()}</p><p className="mt-1 text-muted-foreground">Other deduction: {rule.otherDeduction.toString()}</p></td><td className="px-3 py-3"><p>{formatShortDate(rule.effectiveFrom)}</p><p className="mt-1 text-muted-foreground">to {rule.effectiveTo ? formatShortDate(rule.effectiveTo) : "No end date"}</p></td><td className="px-3 py-3 tabular-nums">{rule._count.transactions.toLocaleString()} transactions</td><td className="px-4 py-3"><span className={`px-2 py-1 text-[10px] font-semibold uppercase ${rule.active ? "bg-emerald-100 text-emerald-900" : "bg-muted text-muted-foreground"}`}>{rule.active ? "Active" : "Historical"}</span></td></tr>)}</tbody></table></div></section>
    <section className="border border-border bg-card"><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Rule audit history</h2></div>{!auditEvents.length ? <p className="p-4 text-sm text-muted-foreground">No rule events recorded.</p> : <ol className="divide-y divide-border">{auditEvents.map((event) => <li key={event.id} className="grid gap-1 px-4 py-3 text-xs sm:grid-cols-[150px_1fr]"><time className="text-muted-foreground">{formatShortDate(event.createdAt)}</time><div><p className="font-semibold">{event.summary}</p><p className="mt-1 text-[10px] text-muted-foreground">{event.actor?.name ?? "System"}</p></div></li>)}</ol>}</section>
  </div>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="border-b border-border px-4 py-3 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold tabular-nums">{value.toLocaleString()}</p></div>; }
