import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, DownloadSimple } from "@phosphor-icons/react/dist/ssr";
import { requireUser } from "@/lib/auth/session";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";
const money = (value: { toString(): string }) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 6 }).format(Number(value.toString()));
const month = (value: Date) => new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric", timeZone: "UTC" }).format(value);

export default async function StatementPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ q?: string; store?: string; country?: string; page?: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const query = await searchParams;
  const page = Math.max(1, Number(query.page) || 1);
  const statement = await prisma.userRoyaltyStatement.findFirst({ where: { id, userId: user.id, royaltyPeriod: { status: "published" } }, include: { royaltyPeriod: true } });
  if (!statement) notFound();
  const where = { userStatementId: id, ...(query.store ? { retailer: query.store } : {}), ...(query.country ? { territory: query.country } : {}), ...(query.q ? { OR: [{ releaseTitle: { contains: query.q, mode: "insensitive" as const } }, { trackTitle: { contains: query.q, mode: "insensitive" as const } }, { isrc: { contains: query.q, mode: "insensitive" as const } }] } : {}) };
  const [transactions, total, storeGroups, territoryGroups, releaseGroups, trackGroups] = await Promise.all([
    prisma.royaltyTransaction.findMany({ where, orderBy: { sourceRowNumber: "asc" }, skip: (page - 1) * 50, take: 50 }),
    prisma.royaltyTransaction.count({ where }),
    prisma.royaltyTransaction.groupBy({ by: ["retailer"], where: { userStatementId: id }, _sum: { userPayableUsd: true }, orderBy: { _sum: { userPayableUsd: "desc" } }, take: 5 }),
    prisma.royaltyTransaction.groupBy({ by: ["territory"], where: { userStatementId: id }, _sum: { userPayableUsd: true }, orderBy: { _sum: { userPayableUsd: "desc" } }, take: 5 }),
    prisma.royaltyTransaction.groupBy({ by: ["releaseTitle"], where: { userStatementId: id }, _sum: { userPayableUsd: true }, orderBy: { _sum: { userPayableUsd: "desc" } }, take: 5 }),
    prisma.royaltyTransaction.groupBy({ by: ["trackTitle"], where: { userStatementId: id }, _sum: { userPayableUsd: true }, orderBy: { _sum: { userPayableUsd: "desc" } }, take: 5 }),
  ]);
  const queryString = new URLSearchParams(Object.entries(query).filter((entry): entry is [string, string] => Boolean(entry[1])));
  return <div className="mx-auto max-w-[1280px] space-y-6"><header className="flex flex-col gap-5 border-b border-border pb-6 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/dashboard/royalties" className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft />Wallet</Link><h1 className="mt-3 text-3xl font-semibold tracking-[-0.04em]">{month(statement.royaltyPeriod.startDate)}</h1><p className="mt-1 text-sm text-muted-foreground">Published royalty statement</p></div><div className="flex gap-2"><a href={`/api/royalties/statements/${id}/export?format=csv`} className="inline-flex h-9 items-center gap-2 rounded-lg border border-border bg-card px-3 text-xs font-semibold hover:bg-muted"><DownloadSimple />CSV</a><a href={`/api/royalties/statements/${id}/export?format=xlsx`} className="inline-flex h-9 items-center gap-2 rounded-lg bg-foreground px-3 text-xs font-semibold text-background"><DownloadSimple />XLSX</a></div></header>
  <section className="grid overflow-hidden rounded-2xl border border-border bg-card sm:grid-cols-3"><Metric label="Net earnings" value={money(statement.userPayableTotal)} /><Metric label="Transactions" value={statement.transactionCount.toLocaleString()} border /><Metric label="Balance status" value={statement.status} border /></section>
  <section className="grid gap-4 lg:grid-cols-4"><Breakdown title="Stores" rows={storeGroups.map((row) => [row.retailer ?? "Unknown", money(row._sum.userPayableUsd ?? { toString: () => "0" })])} /><Breakdown title="Territories" rows={territoryGroups.map((row) => [row.territory ?? "Unknown", money(row._sum.userPayableUsd ?? { toString: () => "0" })])} /><Breakdown title="Top releases" rows={releaseGroups.map((row) => [row.releaseTitle ?? "Unknown", money(row._sum.userPayableUsd ?? { toString: () => "0" })])} /><Breakdown title="Top tracks" rows={trackGroups.map((row) => [row.trackTitle ?? "Unknown", money(row._sum.userPayableUsd ?? { toString: () => "0" })])} /></section>
  <form className="grid gap-3 rounded-xl border border-border bg-card p-4 sm:grid-cols-[1fr_180px_150px_auto]"><input name="q" defaultValue={query.q} aria-label="Search statement" placeholder="Release, track or ISRC" className="h-9 rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-foreground" /><input name="store" defaultValue={query.store} aria-label="Filter by store" placeholder="Store" className="h-9 rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-foreground" /><input name="country" defaultValue={query.country} aria-label="Filter by territory" placeholder="Territory" className="h-9 rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-foreground" /><button className="h-9 rounded-lg bg-foreground px-4 text-xs font-semibold text-background">Filter</button></form>
  <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="border-b border-border bg-muted/45 text-[10px] uppercase tracking-wider text-muted-foreground"><tr>{["Store", "Country", "Release", "Track", "ISRC", "Usage", "Quantity", "Net earnings"].map((label) => <th key={label} className={`px-4 py-3 ${["Quantity", "Net earnings"].includes(label) ? "text-right" : ""}`}>{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{transactions.map((row) => <tr key={row.id}><td className="px-4 py-4">{row.retailer || "—"}</td><td className="px-4 py-4">{row.territory || "—"}</td><td className="px-4 py-4">{row.releaseTitle || "—"}</td><td className="px-4 py-4 font-medium">{row.trackTitle || "—"}</td><td className="px-4 py-4 font-mono">{row.isrc || "—"}</td><td className="px-4 py-4">{row.usageType || "—"}</td><td className="px-4 py-4 text-right tabular-nums">{row.quantity.toString()}</td><td className="px-4 py-4 text-right font-semibold tabular-nums">{money(row.userPayableUsd)}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-border px-4 py-3 text-xs text-muted-foreground"><span>{total.toLocaleString()} transactions</span><div className="flex gap-2">{page > 1 ? <Link className="rounded-md border px-3 py-1.5" href={`?${new URLSearchParams({ ...Object.fromEntries(queryString), page: String(page - 1) })}`}>Previous</Link> : null}{page * 50 < total ? <Link className="rounded-md border px-3 py-1.5" href={`?${new URLSearchParams({ ...Object.fromEntries(queryString), page: String(page + 1) })}`}>Next</Link> : null}</div></div></section></div>;
}
function Metric({ label, value, border = false }: { label: string; value: string; border?: boolean }) { return <div className={`p-5 ${border ? "border-t border-border sm:border-l sm:border-t-0" : ""}`}><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold capitalize tracking-tight">{value}</p></div>; }
function Breakdown({ title, rows }: { title: string; rows: string[][] }) { return <div className="rounded-xl border border-border bg-card p-4"><h2 className="text-sm font-semibold">{title}</h2><div className="mt-3 space-y-2">{rows.length ? rows.map(([label, value]) => <div key={label} className="flex items-center justify-between gap-3 text-xs"><span className="truncate text-muted-foreground">{label}</span><span className="font-medium">{value}</span></div>) : <p className="text-xs text-muted-foreground">No data</p>}</div></div>; }
